name: ci
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Run
      run: make ci

